myapp: program.o Giaithua.o TinhTongChan.o TinhTongLe.o TinhXmuN.o
	gcc -o myapp program.o Giaithua.o TinhTongChan.o TinhTongLe.o TinhXmuN.o
program.o: program.c mylib.h
	gcc -c program.c
Giaithua.o: Giaithua.c
	gcc -c Giaithua.c
TinhTongChan.o: TinhTongChan.c
	gcc -c TinhTongChan.c
TinhTongLe.o: TinhTongLe.c
	gcc -c TinhTongChan.c
TinhXmuN.o: TinhXmuN.c
	gcc -c TinhXmuN.c
